### ISSUE TITLE
vgg_16.ckpt

### ISSUE THREAD

**Issue by suke27** [benbenlijie/style_swap_tensorflow#1]
Hi, could you provide vgg_16.ckpt, it seems need be downloaded
thank you

**Comment by yanx27** [comment]
Hi, I downloaded you VGG-16 and ran you code, but python reported error that the weight and bias of inverse net missiing in your VGG-16, could you help me?
thank you

**Comment by benbenlijie** [comment]
@yanx27 You need to train the inverse net first before you transfer the style. `python main.py -c config/example.json`

**Comment by CJHFUTURE** [comment]
can you expand on training the inverse net? do i need these?
"record_file_name": "e:\\Github\\fast-style-transfer\\datasets\\image_train_*.tfrecord",
  "Image_files": "e:\\Github\\style-swap\\images\\style\\*.jpg",

**Comment by mrgloom** [comment]
Where `*.tfrecord` comes from?

@benbenlijie
